### ISSUE TITLE
Group Icon nicht vorhanden

### ISSUE THREAD

**Issue by havutcuoglu** [netzmacht/contao-leaflet-maps#101]
Hallo,
unter Conrao 4.9.9 ist das Group Icon nicht vorhanden.
Installiert ist die Version 3.2.1
#82 das Problem hatten wir. War zeitlang korrigiert. Jetzt ist es wieder da.

![Bildschirmfoto 2021-04-12 um 13 38 42](https://user-images.githubusercontent.com/11348417/114388832-84c68580-9b94-11eb-8c39-24cec4c453df.png)
![Bildschirmfoto 2021-04-12 um 13 39 23](https://user-images.githubusercontent.com/11348417/114388835-855f1c00-9b94-11eb-8330-aa4beb0195d6.png)

**Comment by dmolineus** [comment]
Behoben mit [94ecdf9](https://github.com/netzmacht/contao-leaflet-maps/commit/94ecdf9d4256bff1e67d34afc40b8ea33c6a2151).
