### ISSUE TITLE
Mixed Content bei Karten-Layer > Kachelvariante > BlackAndWhite

### ISSUE THREAD

**Issue by havutcuoglu** [netzmacht/contao-leaflet-maps#102]
Hallo,

bei der Auswahl von Kartenvariante in Kartenlayer werden die Kartenbilder über HTTP geladen. Tests mit andere Varianten waren in Ordnung. Das Problem tritt nur bei der Auswahl BlackAndWhite auf.

Anbei die Screenshots.

Contao Version: 4.9.9
Leaflet Map Version: 3.2.1

![Bildschirmfoto 2021-04-12 um 13 28 00](https://user-images.githubusercontent.com/11348417/114389348-2f3ea880-9b95-11eb-8e3d-13a270eeaef4.png)
![Bildschirmfoto 2021-04-12 um 13 28 50](https://user-images.githubusercontent.com/11348417/114389353-31a10280-9b95-11eb-80e1-801c3250e99f.png)
![Bildschirmfoto 2021-04-12 um 13 30 03](https://user-images.githubusercontent.com/11348417/114389358-336ac600-9b95-11eb-8605-c1e12a69ecdb.png)

**Comment by Stakdek** [comment]
Same here. 

Versions:
Contao | 4.9.16 
-- | --
Leaflet | 1.7.1

**Comment by Stakdek** [comment]
*push*

**Comment by dmolineus** [comment]
BlackAndWihite wird nicht mehr unterstützt von leaflet-providers.
