### ISSUE TITLE
Not able to display Polylines of Vector Layers

### ISSUE THREAD

**Issue by EarthlingX** [netzmacht/contao-leaflet-maps#105]
While creation and displaying of simple markers works without any problems, it seems to be impossible to create polyline features to display them on a map.

My approach was:

1. Create new layer of type "Vectors"
2. Open new layer "Vectors" and create a new feature of type "Polyline" in it
3. Add vector data: 30.654308,77.22496,27.9364461,72.7065441 (this should be displayed as a straight line)
4. Choose style "Polyline"
5. Add the desired layer to the target Leaflet-map

Open the map and wait for the result: None.

Is there any error in my thinking? Do I have to add something else?

**Comment by dmolineus** [comment]
You have do define each coordinate on a new line.
