### ISSUE TITLE
Felder nur per Tab erreichbar 

### ISSUE THREAD

**Issue by Olli** [netzmacht/contao-leaflet-maps#107]
Das Feld "tileURL" ist nur per Tab erreichbar - ebenso das Feld "Subdomain"
![grafik](https://user-images.githubusercontent.com/1754/134017127-57c61160-f3ca-4d98-9f8b-cffd5e71d42b.png)

**Comment by dmolineus** [comment]
Behoben mit [d498903](https://github.com/netzmacht/contao-leaflet-maps/commit/d49890364544fd679441e2748bb3601bb560c543).
