### ISSUE TITLE
Probleme mit dem Vektor Typ "Kreis" - Radius wird ignoriert

### ISSUE THREAD

**Issue by keved93** [netzmacht/contao-leaflet-maps#119]
Der Vektor als Typ "Kreis" funktioniert nicht. Unter "Radius" kann man eintragen was man möchte (in Meter in diesem Beispiel), dieser wird auf der Karte im Frontend nicht berücksichtigt.

Beispiel: 5000(m) als Wert wurde eingetragen, keine 20m im Frontend dargestellt..

Optional: Es wäre gut, wenn man Umrandung und Fill Farbe direkt im Backend anpassen könnte, mit dem Hinweis, welche Karten das unterstützen würden.

**Comment by dmolineus** [comment]
Behoben in `netzmacht/php-leaflet v1.1.3`
