### ISSUE TITLE
Support more plugins

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-leaflet-maps#14]
Support useful plugins:
- [ ] ~~[Leaflet.MultiTileLayer](http://moonlite.github.io/Leaflet.MultiTileLayer/)~~
- [ ] [Minimap Layers control](https://github.com/jieter/Leaflet.layerscontrol-minimap)
- [ ] [Leaflet.MiniMap](https://github.com/Norkart/Leaflet-MiniMap)
- [ ] [MapQuest Routing](http://developer.mapquest.com/de/web/documentation/plugins/leaflet/v1.0/routing)
- [x] [Leaflet.fullscreen](https://github.com/Leaflet/Leaflet.fullscreen) or http://brunob.github.io/leaflet.fullscreen/
- [ ] [Leaflet.Elevation](https://github.com/MrMufflon/Leaflet.Elevation)
- [ ] [Turbo87/sidebar-v2](https://github.com/Turbo87/sidebar-v2)
- [ ] [Leaflet.NavBar](https://github.com/davidchouse/Leaflet.NavBar)
- [ ] [Leaflet-hash](https://github.com/mlevans/leaflet-hash)
- [ ] [Leaflet.groupedlayercontrol](https://github.com/ismyrnow/leaflet-groupedlayercontrol)
- [x] [Leaflet.ExtraMarkers](https://github.com/coryasilva/Leaflet.ExtraMarkers)

**Comment by BennyK80** [comment]
[Leaflet.GeoSearch](https://github.com/smeijer/leaflet-geosearch)

**Comment by ThomasJanotta** [comment]
and Grayscale Tiles:
https://embed.plnkr.co/plunk/rw9MPC
