### ISSUE TITLE
Uninstall via composer client not working

### ISSUE THREAD

**Issue by hella-schu** [netzmacht/contao-leaflet-maps#39]
After uninstalling contao-leaflet-maps it only disapears from the extension list in the composer client (Paketverwaltung). Maps, layers etc. are still there in the backend menu. Also the  folders system/modules/leaflet and system/modules/leaflet-libs are not removed.

**Comment by dmolineus** [comment]
Could you reproduce it in a test system? I guess that something went wrong when running composer update.

**Comment by dmolineus** [comment]
Closed because of missing feadback. Feel free to reopen if issue occurs again.
