### ISSUE TITLE
Missing alias leads to error notice

### ISSUE THREAD

**Issue by hella-schu** [netzmacht/contao-leaflet-maps#40]
If no alias is given to a layer, creating a new layer is impossible. Alias must be unique, but it is not a required field. Self-filling field (like other alias fields in Contao) would be great.

**Comment by dmolineus** [comment]
The field is not marked as mandatory because an alias generator should automatically create the alias. 

Note for me: 
- Somehow the alias generator is broken. 
- Check how to handle copy actions

**Comment by dmolineus** [comment]
Is fixed in the 2.0.0-beta1 version.
