### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by kikmedia** [netzmacht/contao-leaflet-maps#45]
I just wondered if there will be a version for the new Contao 4 LTS, and asking what I can do for that (besides pull requests for the manager).

**Comment by dmolineus** [comment]
There will definitely a compatible version for Contao 4. The main hurdles for a Contao 4 release are the dependencies of all the progressive cca tools which are used by this extension. 

As these tools were a great thing in Contao 3 the migration to Symfony/C4 is still pending. 
 - [dependency container](https://github.com/contao-community-alliance/dependency-container)
 - [event dispatcher](https://github.com/contao-community-alliance/event-dispatcher)
 - [translator](https://github.com/contao-community-alliance/translator)

I'd prefer to get rid of them at all and use the symfony framework. Unfortunately there's no budget for a new major version of `contao-leaflet-maps` available at the moment. So my goal is to get this extension C4 ready using the old tools.

To cut a long story short: You can:
 - push/support our cca devs to get the tools C4 ready. The is already some progress and hopefully get finished as part of the MetaModels migration
 - Test the early dev version as soon I've started migration

**Comment by kikmedia** [comment]
I will definitely do that. Anyway, I am not as confident as you that there will be a compatible MetaModels release before the end of the year, so we will have to push that even more. 

Again, thanks a lot for all your efforts!

**Comment by dmolineus** [comment]
Update on this topic: I'm working on a release 3.0 which will be Contao 4.4 only release now. As I require a working version until end of october I hope to be able to ask you to test it soon.

**Comment by dmolineus** [comment]
As there is already a an alpha vesion available I close this ticket. Feel free to open issues if any error occur.
