### ISSUE TITLE
Contao 4.4.18 - Map wird nicht angezeigt

### ISSUE THREAD

**Issue by stefan-at-work** [netzmacht/contao-leaflet-maps#56]
Contao 4.4.18 - Installation via Contao Manager / PHP 7.0
Marker wird angezeigt, jedoch **keine** Karte. Im Quelltext (Zeile 548) wird
`div class=" block"Array>`
ausgegeben.
Testinstallation auf [http://spielwiese.contaodev.de/contact-142.html](http://spielwiese.contaodev.de/contact-142.html)

**Comment by dmolineus** [comment]
Du musst eine Karte als Layer definieren und dieses dann der Karte zuweisen.

1. Neue Layer "Vorkonfigurierte Karte" erstellen und Kartenanbieter (z.B. OpenStreetMap) auswählen
2. Layer unter Standardlayer der Karte auswählen

Soll zwischen verschiedenen Kartenlayern geswitcht werden, so muss auch noch das Control-Element Layers angelegt werden. Hier kann man dann mehrere Kartentypen als Basis-Layer definieren, sodass man hin und herschalten kann. Dies ist optional und ersetzt nicht Schritte 1 und 2.

Die Ausgabe des "Array" ist ein Fehler, wenn auch nicht direkt im Zusammenhang mit deinem Problem.

**Comment by paaddyy** [comment]
Wichtig ist es zudem in der Karte eine Zoomstufe auszuwählen, habe festgestellt, dass beim Default "-" die Karte (OpenStreetMap) überhaupt nicht geladen wird.

**Comment by dmolineus** [comment]
Wird kein Zoom-Level angezeigt, erscheint nun eine Infomeldung in der Bearbeitungsmaske.
