### ISSUE TITLE
Keine eigenen ID oder Class Ausgabe möglich

### ISSUE THREAD

**Issue by swinde** [netzmacht/contao-leaflet-maps#58]
Egal ob man die Karte als Modul oder Contentelement ausgibt, ist es nicht möglich eine eigene ID oder eine Klasse auszugeben.

Im Code wird nur dies ausgegeben:
`<div class=" block" array="">`
Die Templates sehen "normal" aus, soweit ich das beurteilen kann.

**Comment by dmolineus** [comment]
Die die Installation aktuell? Welche Contao-Version, Version von netzmacht/contao-leaflet-maps und netzmacht/contao-toolkit ist installiert?

**Comment by swinde** [comment]
Aha! Okay
netzmacht/contao-toolkit | 3.0.6

**Comment by dmolineus** [comment]
Behoben mit 873de89d7c17ff8f6df9f6f79daf6ffa4704017d (erfordert min. netzmacht/contao-toolkit 3.0.6).
