### ISSUE TITLE
Ordering fails on layer control element

### ISSUE THREAD

**Issue by johannes-bittner** [netzmacht/contao-leaflet-maps#72]
When ordering layers using the up/down arrows, the new order is not shown in the frontend element: 
Backend: 
![2019-02-06 15_18_42-leaflet-karten karten teb begegnungsfonds fr kontrollelemente kontrollel](https://user-images.githubusercontent.com/1597697/52350305-8cc09300-2a28-11e9-8c1a-ae8557d09325.jpg)
Frontend: 
![2019-02-06 15_19_08-ubersichtskarte - teb](https://user-images.githubusercontent.com/1597697/52350319-98ac5500-2a28-11e9-9658-8f3d85c29d06.jpg)

**Comment by dmolineus** [comment]
Did I get it right: You can order the layers in the backend and save it but on the map the new order isn't applied, right?

Note for me: Looks like that `ORDER BY sorting` is missing here.
https://github.com/netzmacht/contao-leaflet-maps/blob/4d55b012fd11eaf032979f103695544bde911fee/src/Model/ControlModel.php#L64-L70

**Comment by johannes-bittner** [comment]
Yes, tried again - ordering in the background does no affect the displayed order in the frontend.
