### ISSUE TITLE
Enhancement: Layer controls: output title and alias

### ISSUE THREAD

**Issue by johannes-bittner** [netzmacht/contao-leaflet-maps#73]
I think it would be very useful to output the title of a layer control element on the frontend as well as the alias (for styling).

**Comment by dmolineus** [comment]
I agree that it would be useful. However it's not covered by the default layers control of leaflet (https://leafletjs.com/reference-1.4.0.html#control-layers). So acustom control element would be required.

**Comment by johannes-bittner** [comment]
OK, I naively thought that if the information is collected in the backend, it would be easy to output it (through some sort of template etc.) ... maybe I'll come up with a funding idea
