### ISSUE TITLE
Keine PIN Anzeige bei negativen Koordinaten 

### ISSUE THREAD

**Issue by stefan-at-work** [netzmacht/contao-leaflet-maps#74]
Sofern man es in der Leaflet-Erweiterung mit negativen Koordinaten zu tun bekommt, wird die Karte zwar korrekt angezeigt und zentriert, es wird jedoch der angelegte PIN **nicht** angezeigt.
Beispiel Hotel in London -> 51.50115900,-0.01912800

Contao 4.4.32

**Comment by dmolineus** [comment]
Introduced in [3.1.1](https://github.com/netzmacht/contao-leaflet-maps/compare/3.1.0...3.1.1#diff-f324f6371ca3d732f6b12f7835f8fbbe). Should be:

```diff
-                    $table . '.latitude>0',
-                    $table . '.longitude>0',
+                    $table . '.latitude IS NOT NULL',
+                    $table . '.longitude IS NOT NULL',
```
