### ISSUE TITLE
Missing asset (Icon) stalls all maps display

### ISSUE THREAD

**Issue by johannes-bittner** [netzmacht/contao-leaflet-maps#75]
Due to a problem with another extension that changed UUIDs  (so that upon synchronisation in the file manager, some assets would be marked as deleted, but got another UUID), an individual icon had a mssing asset (like if no file was linked or like if the file had been removed). This resulted in an error message on the frontend even on maps that didn't even use the icon (simple OSM base layer). Is there a way to limit the consequences of such an event to the map(s) that use the missing asset?

**Comment by dmolineus** [comment]
A typical error path would be that an linked icon image got deleted in the file manager. This should indeed not break the whole system.

**Comment by dmolineus** [comment]
I still think that an error should be thrown. Overwise it's not easy to detect something is going wrong. The error now would occur on the client side (JS error) when an icon with invalid image setting is used.
