### ISSUE TITLE
FR: add marker with link

### ISSUE THREAD

**Issue by Aybee** [netzmacht/contao-leaflet-maps#80]
Hallo David, tolle Erweiterung, vielen Dank.

Ich würde mir wünschen, dass dieses Beispiel hier https://leaflet-maps-for-contao.readthedocs.io/de/latest/manual/customize/marker-feature-data.html direkt per Klick im BE ausgewählt werden könnte.

Die Googlemaps auf dieser Seite https://kunsttour-neu-ulm.de/kunsttouren/uebersicht.html sollen nach OpenStreetMap migriert werden. Dort sind mehrere Maps. Die einzelnen Marker sind verlinkt auf interne Seiten. Leider kann man im Feld `featureData` 
```js
{
    "href": "https://contao.rocks"
}
```
keine Inserttags benutzen, geschweige denn den Page-Picker.

Die Möglichkeit hier Inserttags benutzen zu können wäre schonmal eine große Verbesserung, damit man auch mal einen Alias verändern kann ohne das Linkziel zu verlieren.

Ich hoffe, dass dir der Vorschlag gefällt.

**Comment by dmolineus** [comment]
Dass der Inserttag dort nutzbar wird, ist technisch bedingt nicht möglich. Der Inhalt eines Inserttags kann potentiell das JSON zerstören. Als zusätzliches Feature kann ich es mir gut vorstellen.

**Comment by Aybee** [comment]
Feature wäre ja noch besser. Wieviel würde das Funding kosten? Ich kann den Kunden mal fragen, ob er dazu bereit wäre.

**Comment by Aybee** [comment]
Schade.
