### ISSUE TITLE
Load Map after Opt-In to meet EU right

### ISSUE THREAD

**Issue by TB1234** [netzmacht/contao-leaflet-maps#81]
After the latest ECJ judgment, it is very important in the EU, to load a map after a opt-in. So a function is required to ask the user if he want to load the map.

I have serveral solution for other implementations. They work that I got a message with a link:
"Click here to show the map. Personal data can be send to the provider. Hava a look at our privacy policy".

After the user click on the link, the map is shown.

**Comment by dmolineus** [comment]
We are working on a generic consent extension for Contao which will also cover this extension. Maybe there will also be a basic built in solution in this extension.

Fundings are welcome.

**Comment by TB1234** [comment]
> Fundings are welcome.

Further information or details? ;-)

**Comment by dmolineus** [comment]
With release 3.2.0 there is support for Consent tools based on https://github.com/hofff/contao-consent-bridge. I know about two consent tool implementations using the bridge. One is based on usercentrics, the other one is a Contao specific consent tool which also includes sample texts checked by a lawyer for Open Street Map. For more information check https://www.contao.solutions/loesungen/contao-consent.html.
