### ISSUE TITLE
Contao 4 - Group Icon nicht sichtbar

### ISSUE THREAD

**Issue by havutcuoglu** [netzmacht/contao-leaflet-maps#82]
Icon für die Gruppierung wird nicht korrekt eingebunden. Bei einer lokalem Installation fehlt das Icon.
Anstelle:
`#tl_navigation .tl_level_1_group .group-leaflet {
    background: url(/bundles/netzmachtcontaoleaflet/img/leaflet.svg) 3px 2px no-repeat;
}`
das hier verwenden:
`#tl_navigation .tl_level_1_group .group-leaflet {
    background: url(../img/leaflet.svg) 3px 2px no-repeat;
}`

<img width="229" alt="Bildschirmfoto 2019-12-13 um 16 53 34" src="https://user-images.githubusercontent.com/11348417/70813576-fa1c1d80-1dc9-11ea-9367-02dd1c0827b6.png">

**Comment by dmolineus** [comment]
1. Welche Contao-Version wird verwendet?
2. Existiert die Datei `https://DOMAIN/bundles/netzmachtcontaoleaflet/img/leaflet.svg`

Unter Contao 4.4.45 ist alles korrekt mit der obigen Anweisung

![2019-12-13 17 08 43 leaflet](https://user-images.githubusercontent.com/1186266/70814271-6e0af580-1dcb-11ea-8c0c-42e4dff0e1fa.png)

**Comment by havutcuoglu** [comment]
Ich verwende die Contao 4.7.7

Also die Datei existiert nur der Pfad ist nicht korrekt.

Das steht in der css:

`url(/bundles/netzmachtcontaoleaflet/img/leaflet.svg) 3px 2px no-repeat;`

Wenn man aber die url auf

`url(../img/leaflet.svg)`

ändert, ist das problem weg.
Relatives Pfad anstelle absolutes Pfad verwenden.

**Comment by dmolineus** [comment]
Ich verstehe nicht, warum der Pfad nicht korrekt sein soll. Läuft Contao in einem Subverzeichnis (offiziell ja nicht supported)?

**Comment by havutcuoglu** [comment]
Contao läuft lokal unter localhost:8080/my-website/web/index.html

Es ist nur eine Schönheitsfehler, die durch den absoluten Pfad zustande kommt. Wie schon gesagt, wenn du den Pfad von absolute auf relative änderst `url(../img/leaflet.svg)`, sollte das Problem nicht mehr existieren.

**Nochmal zum vergleich**
leaflet group icon: `background: url(/bundles/netzmachtcontaoleaflet/img/leaflet.svg) 3px 2px no-repeat`
layout group icon: `background: url(../../system/themes/flexible/icons/monitor.svg) 3px 2px no-repeat;`
eigene Bereich group icon: `background: url(../img/icon.svg) 3px 2px no-repeat;`

Bei dem 3. Beispiel handelt es sich um die Erweiterungen die ich implementiert habe und diese funktionieren sowohl in localhost auch auf Webspace.

Man muss nicht mehr machen als den Pfad in der backend_global.css auf `url(../img/leaflet.svg) 3px 2px no-repeat;` zu ändern.

Besten Dank und viele Grüße

**Comment by dmolineus** [comment]
Improved in 3.1.6.
