### ISSUE TITLE
Contao 4 - Benennungen von Buttons fehlerhaft

### ISSUE THREAD

**Issue by havutcuoglu** [netzmacht/contao-leaflet-maps#83]
Die Buttons werden nicht korrekt benannt. z.B. wenn man sich in Popups verwalten-Bereich befindet wird Icons verwalten als popups verwalten angezeigt.

<img width="1216" alt="Bildschirmfoto 2019-12-13 um 17 02 03" src="https://user-images.githubusercontent.com/11348417/70813909-9e05c900-1dca-11ea-92cb-693d1cf6ebe6.png">

**Comment by dmolineus** [comment]
Fixed in 3.1.6.
