### ISSUE TITLE
Icon Ausgabe in der Karte

### ISSUE THREAD

**Issue by dp-designpilot** [netzmacht/contao-leaflet-maps#86]
Hallo
Ich habe anhand der Installationsanleitung gearbeitet. Wieso wenn man ein eigenes Icon anlegt erscheint es nicht im Frontend (hab ich eventuell was falsch eingestellt)

Die Karte wird auch initialisiert (also die Karte wird eingebunden) einfach das Icon nicht.

Muss dies denn in einem bestimmten Mass sein ???

**Comment by dmolineus** [comment]
Für Supportanfragen bitte dass Forum nutzen
