### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-leaflet-maps#9]

**Comment by kikmedia** [comment]
Well, as a user for the last year I should be able to provide some documentation. Is there already a place for that?

**Comment by dmolineus** [comment]
I would really appreciate if you start contributing to the documentation. At the moment there is no documentation at all. So any help no matter if english or german would be really great.

I'd prefer managing the documentation using github and the [reStructuredText](http://docutils.sourceforge.net/rst.html) format.

Are you familar familiar with the [reStructuredText](http://docutils.sourceforge.net/rst.html) documentation style and would contribute using git? MetaModels or [Contao-Bootstrap](https://github.com/contao-bootstrap/docs) uses it as well. 

Otherwise using the Contao wiki could be an alternate place.

**Comment by kikmedia** [comment]
Yes I am, yes I will ... ;-)

Do we need a seperate repository for the docs? Should be created by you as the project owner, I think.

**Comment by dmolineus** [comment]
Great! Yes, I'll create a new repo for it with a base structure. Gonna add you as contributor.

**Comment by kikmedia** [comment]
+1

**Comment by dmolineus** [comment]
I created a repo for the docs. It can be found here https://github.com/netzmacht/contao-leaflet-docs. It contains a base structure for the german language. If you prefer writing english I would adjust it. Feel free to extend/change the structure.

The ReadTheDocs page is here http://leaflet-maps-for-contao.readthedocs.org/ and gets autoamtically updated after pushing to the master branch.

If anything else is missing, feel free to ask.

**Comment by sebj54** [comment]
Hi! Thanks for your amazing extension, it is very useful!

I have just one little request: could you add a link to this documentation in the README of this repository? 
Thanks! :)

**Comment by dmolineus** [comment]
Documentation is now added to the composer support section and to the readme as we.

Closing this issue as nothing happened during the last 4 years here. Anyone is still welcome to contribute to this project/documentation.
