### ISSUE TITLE
Markers are not displayed in debug mode on Mac

### ISSUE THREAD

**Issue by zonky2** [netzmacht/contao-leaflet-maps#93]
Markers are not displayed in debug mode on Mac

The `<script>` Tags should inside of this template...
https://github.com/netzmacht/contao-leaflet-maps/blob/master/src/Bundle/Resources/contao/templates/leaflet_map_js.html5

otherwise the information about the template path is entered into the Javascript, e.g.

```
<script>
<!-- START path to template -->
...
<!-- END path to template -->
<script>
```

**Comment by dmolineus** [comment]
The comments needs to be stripped here. Contao templates are not made for rendering anything different than html. For historical reasons the behaviour won't be changed.

**Comment by zonky2** [comment]
Why is the `<script>` not in your template like in Contao?

**Comment by dmolineus** [comment]
Behoben in Version 3.2.2
