### ISSUE TITLE
Automatisches Speichern bei Layer

### ISSUE THREAD

**Issue by zonky2** [netzmacht/contao-leaflet-maps#94]
ich hatte einen Layer offen und wollte mir die Einstellung eines anderen Typs kurz ansehen und habe beim Select was ausgewählt - bin zurück **ohne** Speichern - dennoch wurde der Typ geändert. Das sollte so nicht sein!

**Comment by dmolineus** [comment]
Dies ist das Standardverhalten von Contao DC_Table. Daher kann ich hier nichts ändern.

**Comment by zonky2** [comment]
:(
