### ISSUE TITLE
No content possible with multiple layers

### ISSUE THREAD

**Issue by wugu** [netzmacht/contao-leaflet-maps#97]
If you add content (e.g. of the type file - kml) to at least two layer groups, these will disappear / will not be displayed.

I've tested this in Contao 4.4, 4.9, 4.10, and PHP versions 7.3 and 7.4. 

The added Layer / File - kml) is not displayed in the screenshot. The indentation is blank. 
![2021-02-13-leaflet-bug](https://user-images.githubusercontent.com/5277998/107846454-2bd0b000-6de4-11eb-95dd-ef2b13ba1d9f.png)

**Comment by dmolineus** [comment]
Fixed with [ea293e3](https://github.com/netzmacht/contao-leaflet-maps/commit/ea293e327f618fc6636ca95250585cb681cfd1a2)
