### ISSUE TITLE
Auswahl zwischen Karen von OpenStreetMap (FOSSGIS e.V.) und OpenStreetMap (OpenStreetMap Foundation)

### ISSUE THREAD

**Issue by zonky2** [netzmacht/contao-leaflet-maps#98]
Auswahl zwischen Karen von OpenStreetMap (FOSSGIS e.V.) und OpenStreetMap (OpenStreetMap Foundation) insbesondere im Zusammenspiel mit Contao-Consent

**Comment by dmolineus** [comment]
?

**Comment by zonky2** [comment]
Du hast die Auswahl "OpenStreetMap" - lt. Nicky wird aber zwischen den beiden unterschieden (Tiles kommen entweder aus DE oder UK) und so ist das ja auch im Consent-Manager als Auswahl eingepflegt...

**Comment by zonky2** [comment]
@dmolineus geschlossen weil?

**Comment by dmolineus** [comment]
Problematik des Tickets ist mir nicht klar. Grundlegend gilt, dass die Karten des Provider-Layers von unterschiedlichsten Quellen kommen und es in der Verantwortung des Nutzers liegt entsprechende rechtlichen Bedingungen zu überprüfen. Die jeweiligen Anbieter können hier entnommen werden: https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js

Gerne kannst du mit einen konkreten Vorschlag für eine Verbesserung das Ticket erneut öffnen.
