### ISSUE TITLE
Hilfe-Assistent bei Karten-Layer > Typ ist leer

### ISSUE THREAD

**Issue by zonky2** [netzmacht/contao-leaflet-maps#99]
Hilfe-Assistent bei Karten-Layer > Typ ist leer

https://easycaptures.com/fs/uploaded/1350/0129631901.png

**Comment by dmolineus** [comment]
Behoben mit [18f1cb5](https://github.com/netzmacht/contao-leaflet-maps/commit/18f1cb5756b897c3e8ce133ae51a84d770f2e76e).
